// questions.js
// Interchangeable question packs live here.

const QUESTION_SETS = {
  "party-dk-v1": {
    title: "KBU",
    description: "Let, sjovt, mobil-venligt.",
    questions: [
      { id: "pd1", text: "Hvad betragtes som et normalt blodtryk for en voksen?", options: [ "Ca. 120/80 mmHg", "Ca. 180/110 mmHg", "Ca. 150/90 mmHg", "Ca. 90/60 mmHg" ], correctIndex: 0},
      { id: "pd2", text: "Hvad er førstevalgsbehandling ved anafylaktisk chok?", options: [ "Intramuskulær adrenalin", "Inhalation med beta-2 agonist", "Intravenøs antihistamin", "Intravenøs glukokortikoid" ], correctIndex: 0 },
      { id: "pd3", text: "Hvilken type diabetes kræver altid insulinbehandling?", options: [ "Diabetes insipidus", "Type 2-diabetes", "Type 1-diabetes", "Gestationel diabetes" ], correctIndex: 2 },
      { id: "pd4", text: "Mangel på hvilket vitamin forårsager sygdommen skørbug?", options: [ "D-vitamin", "B1-vitamin", "C-vitamin", "A-vitamin" ], correctIndex: 2 },
      { id: "pd5", text: "Hvilket lægemiddel bruges som antidot ved opioid-overdosis?", options: [ "Naloxon", "Flumazenil", "N-acetylcystein", "Atropin" ], correctIndex: 0 },
      { id: "pd6", text: "Hvad er kroppens største organ?", options: [ "Hjernen", "Huden", "Leveren", "Hjertet" ], correctIndex: 1 },
      { id: "pd7", text: "Hvilken blodtype er universel donor?", options: [ "0-negativ", "0-positiv", "AB-positiv", "A-negativ" ], correctIndex: 0 },
      { id: "pd8", text: "Hvad står 'A' for i ABCDE-princippet i akutmedicin?", options: [ "Airway (frie luftveje)", "Allergi", "Alarm", "Apnø" ], correctIndex: 0 },
      { id: "pd9", text: "Hvilken sygdom er kendetegnet ved tremor, rigiditet og langsomme bevægelser (bradykinesi)?", options: [ "Epilepsi", "Alzheimers sygdom", "Apopleksi", "Parkinsons sygdom" ], correctIndex: 3 },
      { id: "pd10", text: "Hvad er det laveste antal point en patient kan have på Glasgow Coma Scale (GCS)?", options: [ "1", "0", "5", "3" ], correctIndex: 3 },
      { id: "pd11", text: "Hvilken hjernenerve innerverer ansigtets mimiske muskler?", options: [ "N. facialis (VII)", "N. trigeminus (V)", "N. oculomotorius (III)", "N. vagus (X)" ], correctIndex: 0 },
      { id: "pd12", text: "Hvilken sygdom er den hyppigste dødsårsag globalt?", options: [ "Lungekræft", "Slagtilfælde (stroke)", "Iskæmisk hjertesygdom", "Trafikulykker" ], correctIndex: 2 },
      { id: "pd13", text: "En patient hyperventilerer og klager over prikken i fingrene. Hvilken syre-baseforstyrrelse er mest sandsynlig?", options: [ "Respiratorisk acidose", "Metabolisk acidose", "Respiratorisk alkalose", "Metabolisk alkalose" ], correctIndex: 2 },
      { id: "pd14", text: "Hvad er førstevalg af billeddiagnostik ved mistanke om pneumothorax?", options: [ "CT-skanning", "Røntgen af thorax", "Ultralydsskanning", "MR-skanning" ], correctIndex: 1 },
      { id: "pd15", text: "Hvilket vitamin anbefales som tilskud til gravide for at forebygge neuralrørsdefekter?", options: [ "Folinsyre (B9)", "Vitamin B12", "Jern", "Vitamin D" ], correctIndex: 0 },
      { id: "pd16", text: "Hvad hedder knæskallen på latin?", options: [ "Patella", "Fibula", "Femur", "Tibia" ], correctIndex: 0 },
      { id: "pd17", text: "Hvad kaldes en fraktur, hvor knogle-enderne penetrerer huden?", options: [ "Åben fraktur", "Lukket fraktur", "Greenstick-fraktur", "Stressfraktur" ], correctIndex: 0 },
      { id: "pd18", text: "Hvilken knogle brækker typisk ved fald på udstrakt arm hos en ældre person?", options: [ "Clavicula", "Femur", "Calcaneus", "Distal radius" ], correctIndex: 3 },
      { id: "pd19", text: "Hvad er den længste knogle i menneskekroppen?", options: [ "Femur (lårben)", "Tibia (skinneben)", "Columna (rygsøjlen)", "Humerus (overarmsknogle)" ], correctIndex: 0 },
      { id: "pd20", text: "Hvilken nerve risikerer man at lædere ved et brud midt på humerus?", options: [ "N. radialis", "N. medianus", "N. ulnaris", "N. axillaris" ], correctIndex: 0 },
      { id: "pd21", text: "Hvad er ACL i knæet en forkortelse for?", options: [ "Forreste korsbånd", "Menisken", "Bageste korsbånd", "Indvendige sideledbånd" ], correctIndex: 0 },
      { id: "pd22", text: "Hvilken tilstand skyldes kompression af n. medianus ved håndleddet?", options: [ "Karpaltunnelsyndrom", "Thoracic outlet syndrom", "Kubitaltunnelsyndrom", "Tennisalbue" ], correctIndex: 0 },
      { id: "pd23", text: "Hvad kaldes \"tennisalbue\" med et medicinsk udtryk?", options: [ "Rotator cuff syndrom", "Medial epikondylit", "Olecranon bursit", "Lateral epikondylit" ], correctIndex: 3 },
      { id: "pd24", text: "En 40-årig mand hører et smæld i læggen under badminton og kan ikke længere stå på tæer. Hvilken skade er mest sandsynlig?", options: [ "Brud på hælbenet (calcaneus)", "Forstuvning af anklen", "Lægmuskel fibersprængning", "Overrivning af akillessenen" ], correctIndex: 3 },
      { id: "pd25", text: "I hvilken retning går skulderen typisk af led ved en luksation?", options: [ "Inferiort (nedad)", "Superiort (opad)", "Anteriort (fremad)", "Posteriort (bagud)" ], correctIndex: 2 },
      { id: "pd26", text: "Hvilken kræftform er den hyppigste hos kvinder i Danmark?", options: [ "Brystkræft", "Hudkræft", "Lungekræft", "Tarmkræft" ], correctIndex: 0 },
      { id: "pd27", text: "For hvilken kræftsygdom anvendes PSA (prostataspecifikt antigen) som markør?", options: [ "Tyk- og endetarmskræft", "Brystkræft", "Leverkræft", "Prostatakræft" ], correctIndex: 3 },
      { id: "pd28", text: "Hvilken virus kan forårsage livmoderhalskræft?", options: [ "Hepatitis C", "HPV (Human Papillomavirus)", "HIV", "Epstein-Barr virus" ], correctIndex: 1 },
      { id: "pd29", text: "Hvad står 'M' for i TNM-klassifikationen af kræft?", options: [ "Multiple tumorer", "Fjernmetastaser", "Målrecidiv", "Masse (tumorstørrelse)" ], correctIndex: 1 },
      { id: "pd30", text: "Hvilken behandlingsform bruger høj-energi stråling til at dræbe kræftceller?", options: [ "Immunterapi", "Strålebehandling", "Kirurgisk fjernelse", "Kemoterapi" ], correctIndex: 1 }
    ]
  },

  "science-nerd-v1": {
    title: "Introlæge",
    description: "Lidt nørdet, lidt smart.",
    questions: [
      { id: "sn1", text: "En patient har hyperthyreose og exophthalmus (udstående øjne). Hvilken sygdom er mest sandsynlig?", options: [ "Hashimotos thyroiditis", "Graves' sygdom (Basedows)", "Subakut (De Quervain) thyroiditis", "Toksisk multinodøs struma" ], correctIndex: 1 },
      { id: "sn2", text: "Hvilken syre-baseforstyrrelse opstår typisk efter langvarige opkastninger?", options: [ "Respiratorisk acidose", "Respiratorisk alkalose", "Metabolisk alkalose", "Metabolisk acidose" ], correctIndex: 2 },
      { id: "sn3", text: "En patient har ankelødemer, ascites og halsvenestase. Hvilken tilstand passer bedst til disse fund?", options: [ "Nefrotisk syndrom", "Levercirrose", "Højresidig hjerteinsufficiens", "Venstresidig hjerteinsufficiens" ], correctIndex: 2 },
      { id: "sn4", text: "Hvad gives rutinemæssigt til nyfødte for at forebygge blødninger?", options: [ "Jern", "D-vitamin", "Folinsyre", "K-vitamin" ], correctIndex: 3 },
      { id: "sn5", text: "Høfeber (allergisk rhinitis) er et eksempel på hvilken type hypersensitivitetsreaktion?", options: [ "Type I (IgE-medieret)", "Type II (antistofmedieret)", "Type III (immunkompleks)", "Type IV (forsinket)" ], correctIndex: 0 },
      { id: "sn6", text: "Hvilken hjerterytme er karakteriseret ved en \"irregulær-irregulær\" puls?", options: [ "Atrieflagren (forkammerflagren)", "AV-blok grad III", "Atrieflimren (forkammerflimren)", "Sinusarytmi" ], correctIndex: 2 },
      { id: "sn7", text: "Hvilket af følgende er typisk ved en øvre motorneuronskade?", options: [ "Spastisk parese med hyperrefleksi", "Udtalt muskelsvind og atrofi", "Fascikulationer i de påvirkede muskler", "Nedsatte eller ophævede dybe reflekser" ], correctIndex: 0 },
      { id: "sn8", text: "Hvilken bakterie er den hyppigste årsag til samfundserhvervet pneumoni?", options: [ "Legionella pneumophila", "Mycoplasma pneumoniae", "Staphylococcus aureus", "Streptococcus pneumoniae" ], correctIndex: 3 },
      { id: "sn9", text: "En positiv Murphy's tegn under abdominalundersøgelse indikerer typisk:", options: [ "Akut appendicitis (blindtarmsbetændelse)", "Akut pancreatitis (bugspytkirtelbetændelse)", "Akut pyelonefritis (nyrebækkenbetændelse)", "Akut cholecystitis (galdeblærebetændelse)" ], correctIndex: 3 },
      { id: "sn10", text: "Inden for hvor mange timer efter et iskæmisk stroke kan trombolyse typisk iværksættes?", options: [ "Ca. 1 time", "Ca. 12 timer", "Ca. 4,5 time", "Ca. 24 timer" ], correctIndex: 2 },
      { id: "sn11", text: "En patient er varm, rødmosset, hypotensiv og febril med høj puls. Hvilken form for shock er mest sandsynlig?", options: [ "Hypovolæmisk shock", "Septisk shock", "Anafylaktisk shock", "Kardiogent shock" ], correctIndex: 1 },
      { id: "sn12", text: "Hvilken af følgende indgår IKKE i en nyfødts APGAR-score?", options: [ "Muskeltonus", "Respiration", "Blodtryk", "Puls (hjertefrekvens)" ], correctIndex: 2 },
      { id: "sn13", text: "Hvilken tarmsygdom kan involvere hele gastrointestinalkanalen og er karakteriseret ved segmentær ('skip') udbredelse?", options: [ "Colitis ulcerosa", "Divertikulose", "Morbus Crohn", "Irritabel tyktarm (IBS)" ], correctIndex: 2 },
      { id: "sn14", text: "Hvilken almindelig bivirkning ses ved brug af ACE-hæmmere (f.eks. enalapril)?", options: [ "Hårtab", "Lavt blodsukker", "Tør hoste", "Forstoppelse" ], correctIndex: 2 },
      { id: "sn15", text: "Hvilket EKG-fund er typisk ved akut perikarditis?", options: [ "Diffuse ST-elevationer i flere afledninger", "Delta-tak (præeksitation)", "Forlænget QT-interval", "ST-depressioner i V1-V3" ], correctIndex: 0 },
      { id: "sn16", text: "Hvad tester Lachman-testen i knæet for?", options: [ "Ruptur af forreste korsbånd", "Skade på det laterale ledbånd", "Patella-luksation", "Ruptur af mediale menisk" ], correctIndex: 0 },
      { id: "sn17", text: "Hvor i rygsøjlen opstår diskusprolaps hyppigst?", options: [ "Halsryggen (cervikalcolumna)", "Brystryggen (thorakalcolumna)", "Lænderyggen (lumbalcolumna)", "Bækkenet (sakral område)" ], correctIndex: 2 },
      { id: "sn18", text: "Hvilken del af nøglebenet (clavicula) brækker oftest?", options: [ "Laterale (ydre) ende", "Clavicula brækker sjældent", "Midterste tredjedel", "Mediale (indre) ende" ], correctIndex: 2 },
      { id: "sn19", text: "Hvad er den korrekte akutte behandling af et kompartmentsyndrom?", options: [ "Kirurgisk fasciotomi", "Intravenøs antibiotika", "Højt løft af ekstremiteten og is", "Gipsimmobilisering" ], correctIndex: 0 },
      { id: "sn20", text: "Hvilken nerve kan skades ved en anteriort skulderluksation?", options: [ "N. musculocutaneus", "N. radialis", "N. medianus", "N. axillaris" ], correctIndex: 3 },
      { id: "sn21", text: "Hvilken type hoftenær fraktur er hyppigst hos ældre?", options: [ "Pertrokantær femurfraktur", "Acetabulumfraktur", "Collum femoris-fraktur (lårhalsbrud)", "Subtrokantær femurfraktur" ], correctIndex: 2 },
      { id: "sn22", text: "Hvilken menisk i knæet læderes hyppigst?", options: [ "Ingen – menisker brister sjældent", "De læderes lige hyppigt", "Den mediale menisk", "Den laterale menisk" ], correctIndex: 2 },
      { id: "sn23", text: "Et positivt Trendelenburgs tegn (hofte synker ned på modsatte side) tyder på svaghed i:", options: [ "M. quadriceps femoris", "M. gluteus maximus", "Hasemusklerne", "M. gluteus medius/minimus" ], correctIndex: 3 },
      { id: "sn24", text: "Hvilken komplikation frygtes ved brud på os scaphoideum (bådbenet i hånden)?", options: [ "Fejlstilling efter heling (malunion)", "Kompartmentsyndrom i håndleddet", "Avaskulær knoglenekrose", "Infektion i knoglen (osteomyelitis)" ], correctIndex: 2 },
      { id: "sn25", text: "Hvad kaldes testen, hvor man roterer underbenet med knæet bøjet for at afsløre en meniskskade?", options: [ "Lachmans test", "McMurrays test", "Phalens test", "Finkelsteins test" ], correctIndex: 1 },
      { id: "sn26", text: "BRCA1-genmutation hos kvinder medfører særlig øget risiko for:", options: [ "Hudcancer (melanom)", "Tyktarmscancer", "Lungecancer", "Bryst- og ovariecancer" ], correctIndex: 3 },
      { id: "sn27", text: "Hvilken kræftform er den hyppigst forekommende hos børn?", options: [ "Hjernetumor", "Leukæmi", "Knoglekræft", "Lymfekræft (lymfom)" ], correctIndex: 1 },
      { id: "sn28", text: "Tumorlysesyndrom kan medføre livsfarligt forhøjet niveau af:", options: [ "Natrium", "Calcium", "Kalium", "Bicarbonat" ], correctIndex: 2 },
      { id: "sn29", text: "Tumormarkøren CA-125 er primært associeret med hvilken type kræft?", options: [ "Prostatacancer", "Tyktarmscancer", "Lungecancer", "Ovariecancer" ], correctIndex: 3 },
      { id: "sn30", text: "Hvilken kræftsygdom behandles ofte med antiøstrogenet tamoxifen?", options: [ "Brystkræft", "Nyrekræft", "Lungekræft", "Prostatakræft" ], correctIndex: 0 }
    ]
  },

  "spicy-meds-v1": {
    title: "Overlægen(t)",
    description: "Læge-nørd med lidt attitude.",
    questions: [
      { id: "sm1", text: "Hvad betyder det, hvis p-værdien i et studie er 0,03?", options: [ "At studiet har en styrke (power) på 97%", "At sandsynligheden for at resultatet skyldes tilfældighed er 3% (statistisk signifikant)", "At nulhypotesen er sand med 97% sandsynlighed", "At 3% af forsøgspersonerne oplevede effekt" ], correctIndex: 1 },
      { id: "sm2", text: "Hvad er formålet med randomisering i et klinisk forsøg?", options: [ "At øge studiets eksterne validitet", "At fordele kendte og ukendte confounders ligeligt mellem grupperne", "At opnå signifikante resultater lettere", "At sikre at både forsøgsleder og deltagere er blindede" ], correctIndex: 1 },
      { id: "sm3", text: "Hvilken type studie er bedst egnet til at beregne incidens af en sygdom?", options: [ "Case-kontrol-studie", "Tværsnitsstudie", "Kohortestudie", "Case-rapport" ], correctIndex: 2 },
      { id: "sm4", text: "Hvad sker der med en tests positive prædiktive værdi (PPV), hvis prævalensen af sygdommen stiger?", options: [ "PPV ændres ikke", "Testens specificitet stiger", "PPV stiger", "PPV falder" ], correctIndex: 2 },
      { id: "sm5", text: "Hvad kaldes den form for bias, hvor tidligere diagnostik (fx via screening) giver illusion af længere overlevelse uden reel forlængelse af livet?", options: [ "Recall bias", "Selektionsbias", "Confirmation bias", "Lead-time bias" ], correctIndex: 3 },
      { id: "sm6", text: "Hvor stor en andel af observationerne ligger inden for ±2 standardafvigelser i en normalfordeling?", options: [ "Ca. 68%", "Ca. 50%", "Ca. 95%", "Ca. 99,7%" ], correctIndex: 2 },
      { id: "sm7", text: "En patient med type 1-diabetes har Kussmaul-ventilation, høj blodglukose og ketonstoffer i blodet. Hvilken syre-baseforstyrrelse forventes?", options: [ "Metabolisk acidose med højt anion-gap", "Respiratorisk alkalose", "Metabolisk alkalose", "Respiratorisk acidose" ], correctIndex: 0 },
      { id: "sm8", text: "Hvilken syre-baseforstyrrelse ses klassisk ved salicylat (aspirin) forgiftning?", options: [ "Ren metabolisk alkalose", "Blandet metabolisk acidose og respiratorisk alkalose", "Ren metabolisk acidose", "Blandet metabolisk og respiratorisk acidose" ], correctIndex: 1 },
      { id: "sm9", text: "Hvilket tuberkulose-middel kan give synsforstyrrelser (opticusneuritis) som bivirkning?", options: [ "Rifampicin", "Pyrazinamid", "Ethambutol", "Isoniazid" ], correctIndex: 2 },
      { id: "sm10", text: "Hvilket antistof ses forhøjet (positiv test) ved Granulomatose med polyangiitis (Wegeners granulomatose)?", options: [ "ANA", "RF (reumafaktor)", "c-ANCA (PR3)", "p-ANCA" ], correctIndex: 2 },
      { id: "sm11", text: "Hvilken profylakse bør en HIV-patient med CD4-tal under 200 have?", options: [ "Azithromycin mod MAC", "Fluconazol mod svampeinfektion", "Aciclovir mod CMV", "Trimethoprim-sulfamethoxazol mod Pneumocystis jiroveci" ], correctIndex: 3 },
      { id: "sm12", text: "Hvad er den hyppigste årsag til Cushing-syndrom?", options: [ "Kortisolproducerende binyretumor", "Ektopisk ACTH fra fx småcellet lungecancer", "ACTH-producerende hypofyseadenom (Cushings sygdom)", "Langvarig glukokortikoidbehandling (iatrogen Cushing)" ], correctIndex: 3 },
      { id: "sm13", text: "Hvilken primær hjernetumor er hyppigst hos voksne?", options: [ "Astrocytom", "Glioblastom", "Hypofyseadenom", "Meningeom" ], correctIndex: 3 },
      { id: "sm14", text: "Hos IV-stofmisbrugere med endokarditis er den typisk afficerede hjerteklap:", options: [ "Aortaklappen", "Trikuspidalklappen", "Pulmonalklappen", "Mitralklappen" ], correctIndex: 1 },
      { id: "sm15", text: "Hvad er den hyppigste udløsende årsag til akut pancreatitis?", options: [ "Kronisk alkoholmisbrug", "Galdesten", "Medicinske bivirkninger", "Hypertriglyceridæmi" ], correctIndex: 1 },
      { id: "sm16", text: "Hvad er en Monteggia-fraktur?", options: [ "Dobbeltsidig fraktur af både ulna og radius", "Fraktur af proximale ulna med luksation af caput radii", "Fraktur af distale radius med luksation af caput ulna (Galeazzi)", "Fraktur gennem vækstzonen hos et barn (Salter-Harris fraktur)" ], correctIndex: 1 },
      { id: "sm17", text: "Hvilke frakturer anvendes Garden-klassifikationen til at beskrive?", options: [ "Åbne skinnebensbrud (tibia frakturer)", "Albuebrud hos børn", "Rygmarvsskader", "Hoftenære lårhalsbrud (collum femoris frakturer)" ], correctIndex: 3 },
      { id: "sm18", text: "Hvilken Salter-Harris frakturtype (vækstskivefraktur) er hyppigst?", options: [ "Type II", "Type IV", "Type I", "Type III" ], correctIndex: 0 },
      { id: "sm19", text: "Hvad bruges Cobb-vinklen til at måle?", options: [ "Skoliose-grad i rygsøjlen", "Knæets rotationsfejlstilling", "Bevægelighed i hofteleddet", "Vinklen af en hallux valgus deformitet" ], correctIndex: 0 },
      { id: "sm20", text: "En positiv forreste skuffetest af anklen tyder på skade af:", options: [ "Forreste korsbånd i knæet", "Akillessenen", "Lig. talofibulare anterius (FTA) i anklen", "Lig. deltoideum (mediale ledbånd) i anklen" ], correctIndex: 2 },
      { id: "sm21", text: "Hvilken primær knogletumor er hyppigst hos børn og unge?", options: [ "Osteosarkom", "Ewings sarkom", "Kondrosarkom", "Osteoid osteom" ], correctIndex: 0 },
      { id: "sm22", text: "En 80-årig kvinde er faldet og kan ikke rejse sig. Højre ben er forkortet og udadrotateret. Hvilken skade mistænkes?", options: [ "Brud på bækkenringen", "Hoftenær fraktur (formodentlig lårhalsbrud)", "Brud på lårbensskaftet", "Hofteleddets kugle er gået af led (hofte-luksation)" ], correctIndex: 1 },
      { id: "sm23", text: "En overvægtig 13-årig dreng har hoftesmerter og hältende gang. Hvad er en sandsynlig diagnose?", options: [ "Avaskulær nekrose af femurhovedet", "Calvé-Legg-Perthes sygdom", "Epifysiolyse af caput femoris (SCFE)", "Medfødt hoftedysplasi" ], correctIndex: 2 },
      { id: "sm24", text: "En patient med lændesmerter udvikler \"ridebukse-anæstesi\" og urinretention. Hvad er den korrekte håndtering?", options: [ "Observation med sengeleje og smertestillende", "Udredning for nyresten i urinvejene", "Akut udredning (MR) og kirurgisk dekompression for cauda equina-syndrom", "Epidural steroidblokade og genvurdering om 2 uger" ], correctIndex: 2 },
      { id: "sm25", text: "Hvilken muskel/sene tester man ved \"empty-can\" testen i skulderen?", options: [ "M. supraspinatus", "M. biceps brachii (caput longum)", "M. subscapularis", "M. infraspinatus" ], correctIndex: 0 },
      { id: "sm26", text: "Med hvilken hæmatologisk kræftsygdom associeres Philadelphia-kromosomet (t(9;22) BCR-ABL)?", options: [ "Akut myeloid leukæmi (AML)", "Kronisk myeloid leukæmi (CML)", "Akut lymfoblastær leukæmi (ALL)", "Polycythaemia vera" ], correctIndex: 1 },
      { id: "sm27", text: "Hvilken kræftform forårsager flest dødsfald globalt?", options: [ "Lungekræft", "Leverkræft", "Brystkræft", "Tyk- og endetarmskræft" ], correctIndex: 0 },
      { id: "sm28", text: "Hvilken alvorlig bivirkning er særligt forbundet med kemoterapi-medicinen bleomycin?", options: [ "Hjertesvigt", "Svær neuropati", "Hæmoragisk blærebetændelse", "Lungefibrose" ], correctIndex: 3 },
      { id: "sm29", text: "Li-Fraumeni syndrom indebærer en arvelig mutation i hvilket tumorsuppressor-gen?", options: [ "RB1", "BRCA2", "TP53", "APC" ], correctIndex: 2 },
      { id: "sm30", text: "Hvilket target binder antistoffet trastuzumab (Herceptin) til i behandling af brystkræft?", options: [ "CD20", "VEGF", "HER2-receptoren", "PD-1" ], correctIndex: 2 }
    ]
  }
};

module.exports = { QUESTION_SETS };
